sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install pep8 --max-line-length=120
- pip install python-coveralls
script:
- pytest --cov=fatek --cov-report xml
- flake8 .
after_success:
- coverage report
- coveralls

