sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- pip install pep8==1.7.0
- pip install python-coveralls
script:
- py.test --cov=fatek --cov-report xml
- pep8 . --max-line-length=120
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  user: rimek
  password:
    secure: QGh4Nb+YiGJ/Gpe3S6tuazj21x+aSDoyBNJcO3iHS72L7DVOw54yxQ4ymxlir2K7uliwcOEu6rNK+hFsBv2nM6fmOe9gbmCNOuXYtjvX2SjC3ReNeysX49YgYTpGX+uqDgEOr92QMerbDL+le13hOJovV30qwIGHMk8yumC67OM3jRgsbJz3HavpLRc0OaNay+IqWAs9tDIZIGnpPvY8dth4IqAUWeJRv3wrVI63AM/FvJ/InTlgJLXp1/VYbeCCRLa09wNa1nlZ8vwwtblmA8u6X+sZChqtVN9It/Ad5qR3xvBXGBt7zFX+SM2VbXM0PK0MD2nRFS29KMFjeSJ9CZxxFscTkaVawWYDeQjYRAEhLQ+k2LHL64PdkGNcwuJXEqYZFEUm2pM6LJuZVGpVeQhqsTNdwCiwUg1xk7H2A5JKCzG5I5hs9LV9rD8tyCLilGKjYgmb6t8sUHCS+uwsoLtYko6LWJcL55a+EMQD3ZetYDgCiwMl8N/QbAnNWK6AB+RAXkf0yLgmgVEzjIPUYyNLny3tHFK6BMfViT+URvV+5RJ6gFJceqk7wARokwso14PEA1CsYQpy3sZ2dCr/sulg2vSeAghLOAc3HiDxxO3zNPdfKENnaAR1kd4U/BSK+4Ww+xJEY3VDfsPmtWGyPwSggz22a+Q7CEi+hct2Czk=
  on:
    tags: true
