sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- nightly
install:
- pip install -r requirements.txt
- pip install pep8==1.7.0
- pip install python-coveralls
script:
- py.test --cov=fatek --cov-report xml
- pep8 . --max-line-length=120
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  user: rimek
  password:
    secure: T+PgmJkKoDojOcPLSAywRie9jzxqEpQxLPRr1ZNWvTKOXF7G9it+Rne/GOm3TvdfbcYw+9GlHrfq4Bo4ou1cEXuqywiEeNvwBAgMgBb8Iv+ay6N94IGyFOAVJ3sfBpTBMtRuV9cj8gLQXlg0tsG/+muD0KU1b8QIghH+1az8KFkFaLGpYSde7f+YGvcKb6bCzUS8lp50UuGg7N2hxbnyfdcYNMCOqQnxCpQ0I8V5ds2ovB+uUEVeHlMZ2I8B5czjAFzHWzRrAKnjzLWKnBXOjXuRBqArkuJTr6PME60saHmZky0CIShx+fJSi+2P6KJvkJJ+KQtVk4203QDIoZWPUePH+N97cuhbmsPPpCVgLGYk4/tRQiaYYQVHA26O1/gS4wwTLVeyuTi5nANU+9QxdOPhP4AiWN7y1XGav3X6qOuLa2aMpfvVdbuSOiXGKYJ1PvQSFgyITrErX5zs97gKibw4lWrHaDjhee1DhKAtOtmPpaUbyM7LlR16geahb2uYKsbLEJlfKvAMkLFZ1igOefPcuUYtgDQbkoPeRkqhqDD09FF9fkIq/+3bIVazlgPTFcPEFWsJCSoVmBTCsN6foji+AQYPXFY440UBo4S1eyeoGOEFoHc9mpTHMNZX8JL0cpUh+JTLzs7ZIHkxiFlEDjSTJvANNXjwDYA8aiVJxt8=
  on:
    tags: true
